server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;
    error_page 404 /index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Don't cache json files
    location ~* \.json$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        try_files $uri =404;
    }

    # Other static files may be cached for a longer period
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires max;
        log_not_found off;
    }
}
