parent=keycloak

styles=${env.styles:}

scripts=${env.scripts:}

meta=${env.meta:}

TAILCLOAKIFY_ADDITIONAL_SCRIPTS=${env.TAILCLOAKIFY_ADDITIONAL_SCRIPTS:}

TAILCLOAKIFY_ADDITIONAL_STYLES=${env.TAILCLOAKIFY_ADDITIONAL_STYLES:}

TAILCLOAKIFY_ADDITIONAL_META=${env.TAILCLOAKIFY_ADDITIONAL_META:}

TAILCLOAKIFY_HIDE_LOGIN_FORM=${env.TAILCLOAKIFY_HIDE_LOGIN_FORM:}

TAILCLOAKIFY_BACKGROUND_LOGO_URL=${env.TAILCLOAKIFY_BACKGROUND_LOGO_URL:}

TAILCLOAKIFY_BACKGROUND_VIDEO_URL=${env.TAILCLOAKIFY_BACKGROUND_VIDEO_URL:}

TAILCLOAKIFY_HEADER_LOGO_URL=${env.TAILCLOAKIFY_HEADER_LOGO_URL:}

TAILCLOAKIFY_FAVICON_URL=${env.TAILCLOAKIFY_FAVICON_URL:}

TAILCLOAKIFY_FOOTER_IMPRINT_URL=${env.TAILCLOAKIFY_FOOTER_IMPRINT_URL:}

TAILCLOAKIFY_FOOTER_DATAPROTECTION_URL=${env.TAILCLOAKIFY_FOOTER_DATAPROTECTION_URL:}

TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT=${env.TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT:}

TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT_GOOGLE_CAPTCHA=${env.TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT_GOOGLE_CAPTCHA:TRUE}

TAILCLOAKIFY_SHOW_SOCIAL_PROVIDERS_ON_REGISTER=${env.TAILCLOAKIFY_SHOW_SOCIAL_PROVIDERS_ON_REGISTER:}

KEYCLOAKIFY_SPA_DEV_SERVER_PORT=${env.KEYCLOAKIFY_SPA_DEV_SERVER_PORT:}

locales=ar,ca,cs,da,de,el,en,es,fa,fi,fr,hu,it,ja,ka,lt,lv,nl,no,pl,pt-BR,pt,ru,sk,sv,th,tr,uk,zh-CN,zh-TW